### PR TITLE
check in gozk code into vendor/

### PR DESCRIPTION
**Pull request by ghao-ooyala**
No function change.
Check in gozk code instead of using "go get"

### CODE REVIEW

**Comment by budhrg** [comment]
I think it would be good to track libraries with git submodules.

**Comment by edanaher** [comment]
Unfortunately, gozk is hosted on launchpad, and is using Bazaar instead of git.

We really should try using gom instead of submodules; that gives us the version tracking we really want, without having to clone the entire repo (which can be annoyingly slow).  Plus it works with non-git libraries.  (I'm not against gpm/godeps/other package managers; gom just looks nice and similar to Bundler, which we've used extensively with Ruby at Ooyala).

**Comment by ghao-ooyala** [comment]
I agree. check in code is probably the worst way to introduce dependencies. git submodule, when applicable, is not champion of this field either. 

I am willing to give gom a try; but may i have this pull request approved first?

**Comment by edanaher** [comment]
It seems wrong to check in a giant blob of code that we expect to remove; it bloats the git history forever for no good reason.  If you're going to try using gom, why not wait to merge this until you see if that works better?

**Comment by budhrg** [comment]
Closing this PR as it seems irrelevant after moving to gom with [this pull request](https://github.com/ooyala/atlantis-router/pull/26).

**Pull request closed without merging**
